In [3]:
import pandas as pd

df = pd.read_csv("/Users/ethanogogo/Downloads/Top-Apps-in-Google-Play.csv")
df = pd.read_csv("")
df = pd.read_csv("")

df.head(7)

,Unnamed: 0,App Name,App Id,Category,Developer Id,Developer Website,Developer Email,Content Rating,Ad Supported,In App Purchases
0,1,Google Play services,com.google.android.gms,Tools,Google LLC,https://developers.google.com/android/google-p...,apps-help@google.com,Everyone,False,False
1,2,YouTube,com.google.android.youtube,Video Players & Editors,Google LLC,https://support.google.com/youtube/topic/24225...,ytandroid-support@google.com,Teen,True,False
2,3,Google,com.google.android.googlequicksearchbox,Tools,Google LLC,https://www.google.com/search/about/,apps-help@google.com,Everyone,True,False
3,4,Google Maps - Navigate & Explore,com.google.android.apps.maps,Travel & Local,Google LLC,http://maps.google.com/about/,apps-help@google.com,Everyone,True,False
4,5,Google Text-to-Speech,com.google.android.tts,Tools,Google LLC,http://www.google.com/,tts-feedback@google.com,Everyone,False,False
5,6,Google Chrome: Fast & Secure,com.android.chrome,Communication,Google LLC,http://www.google.com/chrome/android,apps-help@google.com,Everyone,False,False
6,7,Gmail,com.google.android.gm,Communication,Google LLC,http://support.google.com/mail/bin/topic.py?hl...,apps-help@google.com,Everyone,True,False

In [11]:
import pandas as pd


df = pd.read_csv("/Users/ethanogogo/Downloads/Top-Apps-in-Google-Play.csv")


df_first_3_cols = df.iloc[:, :3]

df_first_3_cols.head(7)

,Unnamed: 0,App Name,App Id
0,1,Google Play services,com.google.android.gms
1,2,YouTube,com.google.android.youtube
2,3,Google,com.google.android.googlequicksearchbox
3,4,Google Maps - Navigate & Explore,com.google.android.apps.maps
4,5,Google Text-to-Speech,com.google.android.tts
5,6,Google Chrome: Fast & Secure,com.android.chrome
6,7,Gmail,com.google.android.gm

In [13]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("/Users/ethanogogo/Downloads/Top-Apps-in-Google-Play.csv")

# Display header and the first row
df.head(1)

,Unnamed: 0,App Name,App Id,Category,Developer Id,Developer Website,Developer Email,Content Rating,Ad Supported,In App Purchases
0,1,Google Play services,com.google.android.gms,Tools,Google LLC,https://developers.google.com/android/google-p...,apps-help@google.com,Everyone,False,False

In [16]:
import pandas as pd

df = pd.read_csv("/Users/ethanogogo/Downloads/programming language trend over time.csv")

df.head(7)

        Week  Python  Java  C++
0  4/21/2019      55    55   18
1  4/28/2019      52    50   16
2   5/5/2019      56    56   17
3  5/12/2019      56    61   18
4  5/19/2019      57    56   17
5  5/26/2019      55    57   17
6   6/2/2019      54    58   15

In [14]:
import pandas as pd


df = pd.read_csv("/Users/ethanogogo/Downloads/programming language trend over time.csv")


df_first_3_cols = df.iloc[:, :3]

df_first_3_cols.head(7)

        Week  Python  Java
0  4/21/2019      55    55
1  4/28/2019      52    50
2   5/5/2019      56    56
3  5/12/2019      56    61
4  5/19/2019      57    56
5  5/26/2019      55    57
6   6/2/2019      54    58

In [15]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("/Users/ethanogogo/Downloads/programming language trend over time.csv")

# Display header and the first row
df.head(1)

        Week  Python  Java  C++
0  4/21/2019      55    55   18

In [18]:
import pandas as pd

df = pd.read_csv("/Users/ethanogogo/Downloads/archive/BTC_DATA_V3.0.csv")

df.head(7)

        Date    Price     Open     High      Low     Vol. Change %
0  25-Mar-22  44331.0  44013.0  45112.0  43622.0  494.09M    0.72%
1  24-Mar-22  44013.0  42911.0  44251.0  42658.0  491.66M    2.57%
2  23-Mar-22  42912.0  42373.0  43027.0  41795.0  433.96M    1.27%
3  22-Mar-22  42373.0  41022.0  43327.9  40893.0  537.06M    3.29%
4  21-Mar-22  41022.0  41282.0  41532.0  40530.0  406.62M   -0.62%
5  20-Mar-22  41276.0  42241.0  42301.0  40922.0  308.45M   -2.27%
6  19-Mar-22  42233.0  41768.0  42386.0  41529.6  224.59M    1.11%

In [ ]:
import pandas as pd


df = pd.read_csv("/Users/ethanogogo/Downloads/archive/BTC_DATA_V3.0.csv")


df_first_3_cols = df.iloc[:, :3]

df_first_3_cols.head(7)

In [17]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("/Users/ethanogogo/Downloads/archive/BTC_DATA_V3.0.csv")

# Display header and the first row
df.head(1)

        Date    Price     Open     High      Low     Vol. Change %
0  25-Mar-22  44331.0  44013.0  45112.0  43622.0  494.09M    0.72%